############################################################################
#
#  Primary targets:
#    all           - the default target; synonym for 'coq'
#    coq           - builds all .vo files
#    doc           - synonym for 'documentation'
#    install       - copy to coq library location
#    clean         - removes generated files
#
############################################################################

COQC = coqc
COQDEP = coqdep
COQDOC = coqdoc

MODULES	:= hanoi
TEX	:= $(MODULES:%=%.v.tex)

## Library name used for the imports in Coq

# LIBNAME=

## Name of the submakefile generated by coq_makefile

COQMKFILENAME=hanoi_make.mk

############################################################################

.PHONY: all clean coq doc force
.SUFFIXES: .v .vo .v.d .v.glob

all: coq

coq: $(COQMKFILENAME) 
	@$(MAKE) -f $(COQMKFILENAME) 

%.mk : Makefile _%
	coq_makefile -f _$* -o $*.mk

$(COQMKFILENAME): Makefile
	{ echo "-R . $(LIBNAME) " ; ls *.v ; } > _CoqProject && coq_makefile -f _CoqProject -o $(COQMKFILENAME)

install: all
	@$(MAKE) -f $(COQMKFILENAME) install

clean:
	@if [ -f $(COQMKFILENAME) ]; then $(MAKE) -f $(COQMKFILENAME) clean; fi
	rm -f $(COQMKFILENAME) _CoqProject *.mk.conf
	rm -f *.aux *.log *.out *.bbl *.blg *.toc *.v.tex *.pag

force:

$(TEX): force
	$(COQDOC) --gallina --interpolate --latex --body-only -s \
			$(patsubst %.v.tex,%.v,$(notdir $@)) -o $@

doc: relatorio.pdf $(TEX)

relatorio.pdf: relatorio.tex $(TEX) 
	pdflatex relatorio ; pdflatex relatorio ; bibtex relatorio; pdflatex relatorio ; pdflatex relatorio

pdf:
	okular relatorio.pdf&

